# Generated by Django 4.0.4 on 2022-05-03 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TpPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'TipoDePessoa',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('fantasia', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('CpfCnpj', models.CharField(max_length=15, unique=True)),
                ('tp_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pessoa.tppessoa')),
            ],
            options={
                'db_table': 'Fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('CpfCnpj', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('tp_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pessoa.tppessoa')),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
    ]
