# Generated by Django 4.0.4 on 2022-04-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0004_cpfcnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.ForeignKey(default=99999999999, on_delete=django.db.models.deletion.CASCADE, to='Pessoas.cpfcnpj'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpfcnpj',
            name='numero',
            field=models.CharField(default='99999999999', max_length=14, unique=True),
        ),
    ]
