# Generated by Django 4.0.4 on 2022-04-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0005_cliente_cpf_cnpj_alter_cpfcnpj_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpfcnpj',
            name='numero',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
